# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Append 'SNAPSHOT' to version if 'push' happened on 'main'
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
          VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
          mvn versions:set -DnewVersion=$VERSION-SNAPSHOT
      - name: Append branch name to version if 'push' did not happen on 'main' or a tag
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')}}
        run: |
          mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
          VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
          mvn versions:set -DnewVersion=$VERSION-${GITHUB_REF##*/}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            target/*.jar
            !target/*-with-dependencies.jar
      - name: Install gpg secret key
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' ||  startsWith(github.ref, 'refs/tags/')) }}
        run: cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
      - name: Publish to GitHub Packages Apache Maven
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' ||  startsWith(github.ref, 'refs/tags/')) }}
        run: mvn deploy -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -DskipTests -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}